# Generated by Django 6.0.6 on 2026-06-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("tree_planting", "Tree Planting"),
                            ("beach_cleanup", "Beach Cleanup"),
                            ("awareness_talk", "Climate Awareness Talks"),
                        ],
                        max_length=50,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
